### ISSUE TITLE
BUG: 404 links

### ISSUE THREAD

**Issue by ToBeJazz** [BFO-ontology/BFO-2020#101]
Most links on this page are 404's: https://basic-formal-ontology.org/bfo-2020.html

which includes:

- BFO 2020 Term List
- BFO 2020 IRIs
- BFO 2020 Relations

Where can I find these ?

**Comment by johnbeve** [comment]
Website updated in the commit [here](https://github.com/BFO-ontology/BFO-ontology.github.io/commit/fe3bf61b44d66e57bb3fe09fc3ac8d0e23d7e05e). Thank you @ToBeJazz!

**Comment by phismith** [comment]
From: ToBeJazz ***@***.***>
Sent: Tuesday, September 3, 2024 4:44 AM
To: BFO-ontology/BFO-2020 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [BFO-ontology/BFO-2020] BUG: 404 links (Issue #101)


Most links on this page are 404's: https://basic-formal-ontology.org/bfo-2020.html

which includes:
*       BFO 2020 Term List
*       BFO 2020 IRIs
*       BFO 2020 Relations

Where can I find these ?

-

**Comment by ToBeJazz** [comment]
What happens there ?
