### ISSUE TITLE
BUG: 404 on BFO-CCO Office Hours

### ISSUE THREAD

**Issue by jravenel** [BFO-ontology/BFO-2020#108]
**Describe the bug**

**To Reproduce**
1. Go to 'README'
2. Click on 'https://johnbeve.github.io/NCOR-Test/office-hours/'
3. See error '404
There isn't a GitHub Pages site here.

If you're trying to publish one, [read the full documentation](https://help.github.com/pages/) to learn how to set up GitHub Pages for your repository, organization, or user account"

**Screenshots**
![Screenshot 2024-09-18 at 15 20 36](https://github.com/user-attachments/assets/c86977f0-ce05-4a32-aaf8-8e0f8387abb2)

**Comment by johnbeve** [comment]
I'd moved the NCOR page under a GitHub organization and overlooked updating this link. Thanks @jravenel! See https://github.com/BFO-ontology/BFO-2020/commit/12ac8c8b0924ebe5bb049c2173e89f23fc0ad6ad for update
