### ISSUE TITLE
Def of 'first instant of' does not explicitly state that a first instant must be a temporal part of the temporal region of which it is a first instant

### ISSUE THREAD

**Issue by avsculley** [BFO-ontology/BFO-2020#114]
The definition of 'first instant of' does not explicitly specify that the instant in question needs to be a temporal part of the temporal region in question. So, on some plausible reading, the definition permits that a temporal instant that is not a temporal part of a temporal region can be the first instant of that temporal region. 

The definition is as follows

> t first instant of t' =Def t is a temporal instant & t' is a temporal region t' & t precedes all temporal parts of t' other than t

On one reading, it is implied that, necessarily, t is a temporal part of t.' But on another reading this just means _if_ t is a temporal part of t', then t does not precede itself. On this reading it is not necessary that t is a temporal part of t'.

So, my suggestion is to explicitly state that t is a temporal part of t' as follows (suggestion in italicized bold).

>t first instant of t' =Def t is a temporal instant & t' is a temporal region t' **_& t is a temporal part of t'_** & t precedes all temporal parts of t' other than t

**Comment by wceusters** [comment]
Axioms qga-1 and ixz-1 clarify that a first instant doesn't have to be a temporal-part of the temporal region of which it is a first instant. It can also precede it.

**Comment by avsculley** [comment]
This is odd - seems to allow for a temporal region to have two different first instants. The one that is part of the temporal region and the one that precedes it. Not only is this counterintuitive, but it also seems to conflict with the fact that 'has first instant' is a functional property.

**Comment by wceusters** [comment]
> This is odd - seems to allow for a temporal region to have two different first instants. The one that is part of the temporal region and the one that precedes it. Not only is this counterintuitive, but it also seems to conflict with the fact that 'has first instant' is a functional property.

WC: axioms fwf-1 and ogd-1 exclude there to be more than one first, resp. last instant for a given temporal region. So they don't contradict the precedes/part-of alternatives, but restrict the alternatives. You always need to look at all axioms together to obtain a correct picture.

**Comment by avsculley** [comment]
You are right. I was not precise enough in my last message. I should have called the axiom that asserts 'has first instant' is functional into question. This is because it is not the case that domain values for 'has first instant' have one unique domain value. For every possible domain value, the range value can be either the literal first instant of the temporal region or the instant that precedes the temporal region. So, 'has first instant' is not functional. The same applies to 'has last instant.'

**Comment by wceusters** [comment]
> You are right. I was not precise enough in my last message. I should have called the axiom that asserts 'has first instant' is functional into question. This is because it is not the case that domain values for 'has first instant' have one unique domain value. For every possible domain value, the range value can be either the literal first instant of the temporal region or the instant that precedes the temporal region. So, 'has first instant' is not functional. The same applies to 'has last instant.'

No. fwf-1 and ogd-1 clearly state that every temporal region which has a first/last instant has exactly one first/last instant. That precisely one instant can either be preceding or be part of the region. This means that BFO is silent about which of the two is the case, but it is clear about the relation being functional on the 2nd argument.  A function exists when each x-value (input, independent variable) is paired with exactly one y-value (output, dependent variable). Note that for the axioms the premise is that the instant must exist, but if it exists, there is only one. And of course, it is not the same one for all temporal regions.

**Comment by avsculley** [comment]
Thanks for your time and responses. They provide a lot of clarity (and I shall consult the clif next time before positing an issue). It still strikes me as odd that BFO's stance is that for all temporal regions, there is exactly one first instant that is either a temporal part of the temporal region or precedes it. For this relation to be functional it must be that there is some fact of the matter in every case which single temporal instant is the first instant. It cannot be that it is simply a modeling choice that determines which temporal instant is the first instant, since there would be two possible second arguments. While I understand that it is an axiom, and so it's just how BFO does it, I am interested in what theory of time would provide for such a view of first instants. In particular, I am interested in what theory of time might have something to say about when it is the fact of the matter that first instants are part of the temporal region in question, and when (_**and why**_) it is the fact of the matter that first instants precede the temporal region in question. 

**_Most relevant to this issue is the question: why does BFO allow for first instants to precede the temporal regions they are first instants of?_** (the bold italics are just to indicate where this question relates to the preceding paragraph)

**Comment by alanruttenberg** [comment]
Because we're open as to whether intervals are open or closed. Like math (0,1) is the interval 0 to 1 not including 0 and 1. Compare [0,1] which is the interval 0 to 1 inclusive of 0 and 1.

In both cases there is a single and unique first instant, and it is either part of the interval or not.

**Comment by alanruttenberg** [comment]
Only in one of those cases does the first instant precede the interval, the case where the interval is open.

**Comment by phismith** [comment]
We deliberately left this open
As we leave open whether spatial boundaries are parts of things they bound

From: Alec Sculley ***@***.***>
Sent: Sunday, November 10, 2024 5:45 PM
To: BFO-ontology/BFO-2020 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [BFO-ontology/BFO-2020] Def of 'first instant of' does not explicitly state that a first instant must be a temporal part of the temporal region of which it is a first instant (Issue #114)


The definition of 'first instant of' does not explicitly specify that the instant in question needs to be a temporal part of the temporal region in question. So, on some plausible reading, the definition permits that a temporal instant that is not a temporal part of a temporal region can be the first instant of that temporal region.

The definition is as follows

t first instant of t' =Def t is a temporal instant & t' is a temporal region t' & t precedes all temporal parts of t' other than t

On one reading, it is implied that, necessarily, t is a temporal part of t.' But on another reading this just means if t is a temporal part of t', then t does not precede itself. On this reading it is not necessary that t is a temporal part of t'.

So, my suggestion is to explicitly state that t is a temporal part of t' as follows (suggestion in italicized bold).

t first instant of t' =Def t is a temporal instant & t' is a temporal region t' & t is a temporal part of t' & t precedes all temporal parts of t' other than t

-

**Comment by avsculley** [comment]
May I request that this wrinkle is made more explicit in the OWL file? Three options that come to mind are

(1) to change the labels to 'first temporal boundary' and 'last temporal boundary'; 
(2) add some annotation property that explicates this; 
(3) edit the definition such that it is explicit that the temporal instants may either be part of the temporal region, or immediately be preceded by/precede the temporal region, but not both.

**Comment by phismith** [comment]
We already have 'first instant' and 'last instant' in BFO 2020 as boundaries of the relevant temporal interval. One could define the first and last fiat boundaries of a process in terms of first and last instant, but I do not see any urgency to adding new labels.

Changing labels as you propose would, I think, lead to confusion. But in any case you should keep clear the separation between temporal intervals on the one hand and the processes which occupy those intervals on the other.

Both then can either be open or closed.

Recall the distinction between

  1.  [0,1], the closed interval between 0 and 1,
  2.  [0,1) and (0,1], the half-open and half-closed intervals between 0 and 1, and
  3.  (0,1), the open interval between 0 and 1

**Comment by alanruttenberg** [comment]
Closing this as the relations in question have been explained and the suggestion on relabeling rejected.
