### ISSUE TITLE
[201-BFO]: b and c are reversed

### ISSUE THREAD

**Issue by Michaeltlee** [BFO-ontology/BFO-2020#12]
[201-BFO] 
__has continuant part at__ 
Definition: 
~~& _b_ is a __continuant part of__ _c_ __at__ _t_~~
and _c_ is a __continuant part of__ _b_ __at__ _t_

![E07C4BDB-4EF7-4288-A69E-4EF8DE6EABCF](https://user-images.githubusercontent.com/3123045/110266680-f010ac80-7f83-11eb-8ad1-923c5fc9127f.jpeg)

This is the case in `BFO-2020-text.pdf` and `bfo-2020-terms.xlsx`. I didn’t check anywhere else.

**Comment by alanruttenberg** [comment]
Fixed in the next release
