### ISSUE TITLE
Missing clause in axiom about the bearer of a specifically dependent continuant participating when the dependent participates

### ISSUE THREAD

**Issue by alanruttenberg** [BFO-ontology/BFO-2020#2]
Documented as [Errata #2](https://github.com/BFO-ontology/BFO-2020/blob/0fffdd76483ecfb877936c7052e48fe071581a2a/21838-2/errata.txt#L46)

- In the PDF axiom 6
- In the common logic 4
- Not numbered in the prover9 source

Since this is a logic error, the model will be rechecked once fixed.

Thanks to Werner Ceusters

**Comment by alanruttenberg** [comment]
Werner Ceuster comments, regarding the axiom
> ... it might also be that textual description is wrong. I don’t see why it[_tp_] should be part of the time[_t_], and if so, than rather the other way round, the time the SDC participates is part of the time the IC participates. The SDC cannot survive without the IC. At the other hand, the SDC might cease to exist while the IC still exists.

This is a good point. I think it should be that whenever the SDC participates, the bearer participates - no discussion of parts necessary. I don't think we worry about the case of the SDC participating without the bearer - the antecedent conditions on the SDC participating. The current version, if fixed as I initially thought I would,  allows for models where the SDC participates at some times that the bearer does not.  I can't think, at the moment, of that being a plausible situation.

Some things to check:

- Can the stronger version (bearer participates whenever dependent does) be proven from the current axiom and the rest of the theory? In that case the formula would be misleading but still adequate, and the model wouldn't need to be checked again.

- The analogous axiom for GDC participation should be checked for the same issue.

For reference, here's the axiom as it is now. The bug is that It's missing a clause connecting _t_ to _tp_. The question the comment evokes is whether we need _tp_ at all.

```
(forall (sdc p t)
 (if
  (and (instance-of sdc specifically-dependent-continuant t)
   (participates-in sdc p t))
  (exists (tp ic)
   (and (instance-of tp temporal-region tp)
    (instance-of ic independent-continuant tp)
    (not (instance-of ic spatial-region tp))
    (specifically-depends-on sdc ic) (participates-in ic p tp)))))
```

**Comment by phismith** [comment]
How does this impact the material on the BFO-2020 official ISO site
(Since ISO is being slow to react, we can in principle still upload a very
slightly new version of some of the files)
BS

**Comment by alanruttenberg** [comment]
The GitHub site uses "version control". That means each time change is
made, via a "commit" the site / contents can be changed while still
preserving all the historical versions.

The contents originally associated with the release are "tagged". This
makes it possible to change the view to see the whole site exactly as it
was at the commit the tag is put at or you can see it as it is now. In my
exchange with Ron I told how to link to both the tagged/authoritative
version as well as the current version. If you follow his link, or if you
select the authoritative version tag on GitHub, you see the authoritative
version.

If you just go the GitHub normally then you see the latest version, which
will be updated as issues are noted and fixed. There's also a way, when on
the project page, to choose to see the authoritative version.

If you want, the tag for the authoritative version can be moved forward to
the commit in which the fixes are made. Entirely your judgement call as to
whether to do that or not.

Note that I won't be able to commit the fixes for issue 2 until next week
after I've had time to check that they don't break anything. But Issue 1 is
strictly about documentation. Fixing that has no logical consequence so I
can update that sooner.

Ron's page will be on the BFO website. I will also make a note on the
GitHub project page explaining the tag versus current version issue, and
give instructions for visitors on how to manually choose to view the tagged
authoritative version.

Alan

On Wednesday, September 23, 2020, Barry Smith <notifications@github.com>
wrote:
> How does this impact the material on the BFO-2020 official ISO site
> (Since ISO is being slow to react, we can in principle still upload a very
> slightly new version of some of the files)
> BS
>
> On Tue, Sep 22, 2020 at 4:42 PM Alan Ruttenberg <notifications@github.com>
> wrote:
>
>> Documented as Errata #2
>> <
https://github.com/BFO-ontology/BFO-2020/blob/0fffdd76483ecfb877936c7052e48fe071581a2a/21838-2/errata.txt#L46

**Comment by alanruttenberg** [comment]
fixed in next release
