### ISSUE TITLE
Why isn't exists-at in the relations table or in OWL

### ISSUE THREAD

**Issue by alanruttenberg** [BFO-ontology/BFO-2020#27]
I had, at some point, a worry about whether it would be a problem in OWL. Articulate a problem or add it as a relation.

Thanks to Hedi Karray for raising this.

**Comment by dlutz2** [comment]
'exists at' does seem to be in the OWL but not in the relations table. It doesn't have a domain/range specified in the OWL, presumably entity(?)/temporal region.

**Comment by alanruttenberg** [comment]
fixed in the next release
