### ISSUE TITLE
Typo in Defs for Participant rels

### ISSUE THREAD

**Issue by mark-jensen** [BFO-ontology/BFO-2020#3]
`has participant at some times` 
"p has participant c at some time =Def for some time t (b is a process, c is a continuant, and c participates in p some way at t"

`has participant at all times`
"p has participant c at all times =Def for all times t, b exists at t implies (b is a process, c is a continuant, and c participates in p some way at t)"

in both cases "b is a process" should read "p is a process"

in the all-times rel, "b exists at t" should read 'p exists at t"

**Comment by alanruttenberg** [comment]
Thanks for finding that!

**Comment by alanruttenberg** [comment]
A fix will be made to both the definitions in the OWL file, and the text of the ISO spec.
