### ISSUE TITLE
Typo in Relational Quality Definition

### ISSUE THREAD

**Issue by ameliakahn** [BFO-ontology/BFO-2020#32]
The text definition for Relational Quality reads:
 "b is a relational quality =Def b is a quality and there exists c and d such that **b and c are not identical**, & b s-depends on c & b s-depends on d" 

I think this should say that the two relata, c and d, are not identical, rather than the b, the relational quality, isn't identical to one of the relata.  (If what's intended is that no relational quality relates itself to anything else, then the definition should include that b and d are not identical, as well.  However, I don't think that was the idea.)

**Comment by johnbeve** [comment]
Thank you @ameliakahn. OWL files have been updated as you've suggested. See:
https://github.com/BFO-ontology/BFO-2020/commit/4d00938e1ccf1ba16ce75223ee1b728b681e4faa
https://github.com/BFO-ontology/BFO-2020/commit/775be6d920b63a0e985639046acddf592565a157
