### ISSUE TITLE
Typographic Consistency

### ISSUE THREAD

**Issue by neilotte** [BFO-ontology/BFO-2020#33]
Two tasks that may aid in generating documentation from the OWL file: 

1. Ensure all definition properties are set in sentence case and terminate with a period. 
2. Set separate examples as their own value of a property rather than set a list as the object of a skos:example.

There are probably others too...

**Comment by johnbeve** [comment]
Addressed typographic consistency throughout in merge https://github.com/BFO-ontology/BFO-2020/pull/73

Thanks!
