### ISSUE TITLE
Version that's supposed to not have temporalized relations does

### ISSUE THREAD

**Issue by alanruttenberg** [BFO-ontology/BFO-2020#35]
Generation of this artifact worked earlier on, but must have got broken along the line. Replace it with a fixed version.

**Comment by alanruttenberg** [comment]
fixed

**Comment by neilotte** [comment]
This file appears to have temporalized relations again: [bfo-2020-without-some-all-times.owl](https://github.com/BFO-ontology/BFO-2020/blob/21838-2/21838-2/owl/bfo-2020-without-some-all-times.owl)

**Comment by alanruttenberg** [comment]
You are looking at an old branch. Always look at master.
The duplicate bfo.owl bfo-2020.owl will be fixed momentarily
Alan

**Comment by neilotte** [comment]
@alanruttenberg  -- I was going by the BFO2020 home page here: https://basic-formal-ontology.org/bfo-2020.html

which contains "An RDF/XML format of BFO 2020 without the temporalized object properties which (corresponding to ISO/IEC:21838-2 A.1.2) is available here [bfo-2020-without-some-all-times.owl](https://github.com/BFO-ontology/BFO-2020/blob/21838-2/21838-2/owl/bfo-2020-without-some-all-times.owl) ." -- where the end link resolves to this old file. 

It sounds like this link on this page should also be updated.

**Comment by alanruttenberg** [comment]
Ok, thanks for pointing that out. I also fixed the links on the bfo-2020
page to point to the master branch.
