### ISSUE TITLE
Consistency proof for 8792dde commit

### ISSUE THREAD

**Issue by mereolog** [BFO-ontology/BFO-2020#40]
Could you share the details of how you checked the consistency of [8792dde](https://github.com/BFO-ontology/BFO-2020/commit/8792dde1f5702f291adc1c4c8ff83cff28d91be1)?

I tried to use a number of reasoners, including the ones accessible from https://www.tptp.org, but all of them timed out after reasonable time limits.

**Comment by alanruttenberg** [comment]
I don't know about a specific commit but the the consistency proof is shown by showing there's a [model](https://github.com/BFO-ontology/BFO-2020/tree/master/21838-2/model).  There's a clausetester (LADR tools) file to check it but clausetester blows out the stack when I try to use it. Instead I use the equivalent of clausetester that I wrote. Not sufficiently documented, but you can [check it out](https://github.com/alanruttenberg/lsw2/blob/c5d9a29a1d097ae7dc2efce738aee297be630fc6/logic/formula-tester.lisp#L591) 
Please close the issue if you are satisfied with this response.

**Comment by mereolog** [comment]
Thanks for this clarification.

However, I am after being able to verify the consistency of BFO _automatically_, so I would like to use a reasoner/model finder to check whether the model you refer to is indeed a model of BFO (at a given commit).
I think that at the moment this is not possible because some of CLIF axioms seem to be ill-formed - see: https://github.com/BFO-ontology/BFO-2020/issues/47.

**Comment by wceusters** [comment]
eom-1 was found to be incorrect last year, but perhaps not updated yet.
wsg-1 contained also a mistake, found at the same time.

**Comment by alanruttenberg** [comment]
these should be fixed now

**Comment by mereolog** [comment]
The fix solves this issue, but see https://github.com/BFO-ontology/BFO-2020/issues/48.
