### ISSUE TITLE
Elucidation and Definition columns seem swapped for A.1.2.7 and A.1.2.8 in bfo-2020-terms

### ISSUE THREAD

**Issue by psiotwo** [BFO-ontology/BFO-2020#43]
... what is an Elucidation there looks more like a Definition and vice versa, or alternatively (to keep it better aligned with their A.1.2.5 and A.1.2.6 counterparts) the Elucidation should be rephrased into a Definition and vice versa.

**Comment by alanruttenberg** [comment]
Thank you. This is fixed now.
