### ISSUE TITLE
proper occurrent part of is not declared transitive

### ISSUE THREAD

**Issue by alanruttenberg** [BFO-ontology/BFO-2020#46]
Reported by Stefan Schulz.
It's declared transitive in the FOL, but in an oversight it wasn't on the list of transitive properties for which the OWL transitivity axiom was added.

**Comment by wceusters** [comment]
> Reported by Stefan Schulz. It's declared transitive in the FOL, but in an oversight it wasn't on the list of transitive properties for which the OWL transitivity axiom was added.

Where is it in FOL, i.e. the ISO version? kad-1 declares it for occurrent-part-of with as consequence that if 'a pop b' and 'b pop c' only follows that 'a op c'.

**Comment by alanruttenberg** [comment]
Sorry, my mistake - it's declared to be a theorem in the source from which the CL is generated, which is where I looked, and theorems are not included in the common logic.  If follows from the definition of proper-occurrent-part-of, transitivity of occurrent-part-of and antisymmetry of occurrent-part-of:  okr-1, kad-1, and xlu-1

It isn't in the OWL because all the OWL assertions are generated from specs and then verified provable, and the list for which there should be transitive assertions inadvertently omitted proper-occurrent-part-of. I've fixed the source but not regenerated the OWL yet.

If the forward relation is transitive, then that the inverse is transitive is also a theorem.

**Comment by wceusters** [comment]
Ok, but unless I'm wrong, you don't need xlu-1 to prove it:
              Proper-occurrent-part-of 	a	b	input			(1)
              Occurrent-part-of		a	b	okr-1/(1)		        (2)
Not	      =				        a	b	okr-1/(1)		        (3)
              Proper-occurrent-part-of 	b	c	input			(4)
              Occurrent-part-of		b	c	okr-1/(4)		        (5)
Not	      =				        b	c	okr-1/(4)		        (6)
	      Occurrent-part-of		a	c	kad-1/(2)/(5)		(7)
Not	      =				        a	c	(3)/(6)			(8)
              Proper-occurrent-part-of  a	c	okr-1/(8)/(7)		!

**Comment by alanruttenberg** [comment]
I never trust myself to reason. Here's a transcript of what I did. First I ask to prove the transitivity. Then I ask for how it was proved, and it includes the antisymmetry. Then I try to prove it without transitivity. Then I ask for a model where the two axioms are true but the transitivity isn't.

```lisp
>> (vampire-prove '((:kind :occurrent-mereology))
                 '(:forall (?x ?y ?z) (:implies (:and (proper-occurrent-part-of ?x ?y) (proper-occurrent-part-of ?y ?z))
                                          (proper-occurrent-part-of ?x ?z))))
:proved

>> (get-vampire-proof-support)

(:definition-of-proper-occurrent-part-of :occurrent-part-of-is-antisymmetric :occurrent-part-of-transitive)

>> (vampire-prove '(:definition-of-proper-occurrent-part-of :occurrent-part-of-transitive) 
                      '(:forall (?x ?y ?z) (:implies (:and (proper-occurrent-part-of ?x ?y) (proper-occurrent-part-of ?y ?z))
                                               (proper-occurrent-part-of ?x ?z))))

:failed

>> (z3-find-model '(:definition-of-proper-occurrent-part-of :occurrent-part-of-transitive 
                        (:not (:forall (?x ?y ?z) (:implies (:and (proper-occurrent-part-of ?x ?y) (proper-occurrent-part-of ?y ?z))
                                               (proper-occurrent-part-of ?x ?z))))))

#<z3-model domain size 3, 2 predicates, 15 tuples>

>> (pprint-model *)
(proper-occurrent-part-of c2 c3)
(proper-occurrent-part-of c2 c1)
(proper-occurrent-part-of c3 c2)
(proper-occurrent-part-of c3 c1)
(proper-occurrent-part-of c1 c2)
(proper-occurrent-part-of c1 c3)
(occurrent-part-of c2 c2)
(occurrent-part-of c2 c3)
(occurrent-part-of c2 c1)
(occurrent-part-of c3 c2)
(occurrent-part-of c3 c3)
(occurrent-part-of c3 c1)
(occurrent-part-of c1 c2)
(occurrent-part-of c1 c3)
(occurrent-part-of c1 c1)
```

**Comment by alanruttenberg** [comment]
Here's a smaller model (courtesy of [mace4)](https://www.cs.unm.edu/~mccune/prover9/)
```lisp
(occurrent-part-of c1 c1)
(occurrent-part-of c1 c2)
(occurrent-part-of c2 c1)
(occurrent-part-of c2 c2)
(proper-occurrent-part-of c1 c2)
(proper-occurrent-part-of c2 c1)
```

**Comment by alanruttenberg** [comment]
fixed now
