### ISSUE TITLE
Multiple copies of BFO without-some-all-times

### ISSUE THREAD

**Issue by neilotte** [BFO-ontology/BFO-2020#49]
See https://github.com/BFO-ontology/BFO-2020/tree/master/21838-2/owl

It looks like there's:

- bfo-2020-without-some-all-times.owl
- bfo-without-some-all-times.owl
- bfo-without-some-all-times.ttl.

The first is called out in the ReadMe, but the second two are not. Is this an error?

**Comment by alanruttenberg** [comment]
It was an error and fixed in 331be01215351d1571ad7419972422fdbe6e3cc7
