### ISSUE TITLE
Request for a picture of BFO2020

### ISSUE THREAD

**Issue by mhodki** [BFO-ontology/BFO-2020#5]
It would be very helpful for users to have a picture of the classes in BFO 2020 on one page. If it could be made in a program CMaps and the cmaps file made available (in addition to jpg, pdf etc) that would be very useful. Thanks.

**Comment by zhengj2007** [comment]
Hi @alanruttenberg, I have the BFO 2020 class hierarchy picture in pptx format. Do you want it? If so, I can send to you.

**Comment by alanruttenberg** [comment]
Hi @zhengj2007 . Yes, thanks!
