### ISSUE TITLE
[abo-1] identifier is used for two different axioms in universal-declaration.cl

### ISSUE THREAD

**Issue by wceusters** [BFO-ontology/BFO-2020#53]
(cl:comment "history is subclass of process [abo-1]"
    (forall (t x)
     (if (instance-of x history t) (instance-of x process t))))

  (cl:comment "two-dimensional-spatial-region is subclass of spatial-region [abo-1]"
    (forall (t x)
     (if (instance-of x two-dimensional-spatial-region t)
      (instance-of x spatial-region t))))

**Comment by alanruttenberg** [comment]
On the next commit, "history is subclass of process" will be [zuj-1]
