### ISSUE TITLE
Triple use of [qga-1] in CLIF files

### ISSUE THREAD

**Issue by wceusters** [BFO-ontology/BFO-2020#54]
It appears as the following axiom in both order.cl and temporal-region.cl
  (cl:comment "A first instant is either part of an extended region or precedes it [qga-1]"
    (forall (f i)
     (if
      (and (instance-of f temporal-instant f)
       (instance-of i temporal-region i)
       (not (instance-of i temporal-instant i)) (has-first-instant i f))
      (iff (not (temporal-part-of f i)) (precedes f i)))))

It is used for a different axiom in universal-declaration.cl:
  (cl:comment "spatial-region is a universal [qga-1]"
    (universal spatial-region))

**Comment by alanruttenberg** [comment]
On the next commit "spatial-region is a universal" will be [rej-1]
