### ISSUE TITLE
Two more axiom identifiers that are not unique

### ISSUE THREAD

**Issue by wceusters** [BFO-ontology/BFO-2020#55]
%   xlm-1: 
%     universal-declaration.cl: fiat-point is subclass of continuant-fiat-boundary [xlm-1]
%     spatial.cl: located-in is transitive at a time [xlm-1]
%   eeg-1: 
%     temporal-region.cl: If a has-temporal-part b then if a is an instance of one-dimensional-temporal-region then b is an instance of one-dimensional-temporal-region or zero-dimensional-temporal-region  [eeg-1]
%     temporalized-relations.cl: has-material-basis at all times [eeg-1]

**Comment by alanruttenberg** [comment]
On the next commit 
- "has-material-basis at all times" will be [qdl-1]
- "located-in is transitive at a time" will be [ets-1]

**Comment by wdduncan** [comment]
Are the ids `[qdl-1]`, `[ets-1]`, etc. supposed to be in the [BFO 2020 Term List](https://github.com/BFO-ontology/BFO-2020/blob/master/21838-2/bfo-2020-terms.xlsx) spreadsheet? I am not finding them.

**Comment by alanruttenberg** [comment]
No, they are identifiers for axioms, whereas the term list is of classes and relations. They appear in the Common Logic and PDF renderings.
