### ISSUE TITLE
Range of exists at

### ISSUE THREAD

**Issue by johnbeve** [BFO-ontology/BFO-2020#63]
The textual definition indicates the range of 'exists at' should be 'temporal region' but there is currently no range constraint. 

Was this overlooked (in which case I can open a PR to fix) or was this by design?

**Comment by alanruttenberg** [comment]
Not intention, just didn't have a heuristic at the time that generated that. We need a mechanism for contributed axioms, since the main files are generated. At a new release I would incorporated thus-far submitted axioms as part of the release process.

**Comment by johnbeve** [comment]
Updated in merge: https://github.com/BFO-ontology/BFO-2020/pull/73
