### ISSUE TITLE
'Event' 

### ISSUE THREAD

**Issue by neilotte** [BFO-ontology/BFO-2020#68]
Please consider adding 'Event' as a skos:altLabel for the class 'Process'

**Comment by johnbeve** [comment]
Any objections? @alanruttenberg

**Comment by alanruttenberg** [comment]
I don't have objections, but please check with Barry as he tends to care about such things.

**Comment by johnbeve** [comment]
@alanruttenberg Barry is on board. 

I think the addition is well-motivated given CCO's Event Ontology; there's a larger conversation to have wrt whether there should be an 'event' subclass of BFO:Process, but in the meantime I'lll update with an altlabel. 

FYI: I create a "BFO2020 Task" project to organize issues like this on a kanban board.

**Comment by johnbeve** [comment]
Event altlabel added to directory reshuffling PR for bfo-core and bfo-tr extension of core: 
[bfo-core](https://github.com/BFO-ontology/BFO-2020/pull/67/commits/2814c823b93e1c65af16801418202113c4e1c338)
[bfo-tr](https://github.com/BFO-ontology/BFO-2020/pull/67/commits/5fca4da7d37c67faaae725464d9024ea2781d79c)

**Comment by johnbeve** [comment]
Resolved in recent update.
