### ISSUE TITLE
BUG: Minor issue with missing space in comment on axiom [uns-1

### ISSUE THREAD

**Issue by hoganwr** [BFO-ontology/BFO-2020#77]
The following comment is missing a space between the words "argument" and "when"

  (cl:comment "exists-at is dissective on first argumentwhen it is a continuant [uns-1]"

It should be:

  (cl:comment "exists-at is dissective on first argument when it is a continuant [uns-1]"

**Comment by hoganwr** [comment]
It's in the file src/common-logic/existence-instantiation.cl

**Comment by johnbeve** [comment]
@hoganwr Updated here https://github.com/BFO-ontology/BFO-2020/commit/83e25b9b0e1f5c1cdf305a884a7980c29e618558

Thanks!
