### ISSUE TITLE
Update obolibrary PURL

### ISSUE THREAD

**Issue by tmprd** [BFO-ontology/BFO-2020#78]
http://purl.obolibrary.org/obo/bfo/2020/bfo.owl points to the old location of bfo-2020.owl in this repo, which now yields a 404 response.

I think now there should be a PURL which points to [bfo-core.ttl](https://github.com/BFO-ontology/BFO-2020/blob/master/src/owl/bfo-core.ttl). Would it be http://purl.obolibrary.org/obo/bfo/2020/bfo-core.ttl ?

I'm not familiar with best practices for https://github.com/OBOFoundry/purl.obolibrary.org which I think manages this. This seems like a tricky thing to test prior to changing the directory or filenames referenced on a particular branch.

**Comment by ThHanke** [comment]
Can confirm that bug. Redirect must be corrected here:
https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/bfo.yml
At least all links including string "BFO-ontology/BFO-2020" are broken!

**Comment by johnbeve** [comment]
@ThHanke @tmprd Thanks to you both; @alanruttenberg and I are working out a solution and will hopefully have this resolved today. 

For others observing the issue: redirects need correcting owing to changes from this PR: https://github.com/BFO-ontology/BFO-2020/pull/73

**Comment by linikujp** [comment]
post related issues opened in BFO repo here:
https://github.com/BFO-ontology/BFO/issues/235
https://github.com/BFO-ontology/BFO/issues/236  - this is about license.

**Comment by johnbeve** [comment]
@tmprd PURLs updated in this PR: https://github.com/OBOFoundry/purl.obolibrary.org/pull/971

@linikujp dashboard issues addressed too, see: https://github.com/BFO-ontology/BFO/issues/235
