### ISSUE TITLE
BUG: spatial regions cannot bear qualities

### ISSUE THREAD

**Issue by wdduncan** [BFO-ontology/BFO-2020#86]
At [Enhanced Object-Based Production Conference part two](https://ncorwiki.buffalo.edu/index.php/Enhanced_Object-Based_Production_Conference_part_two) the issue was raised as to why qualities cannot specifically depend on spatial regions. See definition for specifically depends on:
> (Elucidation) specifically depends on is a relation between a specifically dependent continuant b and specifically dependent continuant or independent continuant that is **not a spatial region** c such that b and c share no parts in common & b is of a nature such that at all times t it cannot exist unless c exists & b is not a boundary of c

I can see why it may be odd for a spatial region to bear a disposition, but it seems to me that a spatial region should be able to bear a quality (e.g., shape).

**Comment by alanruttenberg** [comment]
If you are using spatial regions in an ontology you most likely shouldn't be. Can I ask what you are trying to represent?

**Comment by wdduncan** [comment]
This topic came up at the conference. I don't have a particular use case. Perhaps @johnbeve or @phismith want to weigh in.

In general, it seems odd that there exists a types independent continuant that can't bear a quality. Perhaps spatial region should be a type of IC? It also seems quite sensible that an line (i.e., one-dimensional spatial region) has a length, and a plane (i.e., two-dimensional spatial region) has a height and width.

**Comment by johnbeve** [comment]
@alanruttenberg Sending over my slides from the talk for context.

**Comment by alanruttenberg** [comment]
Haven't heard any commentary. As BFO is already defined so that spatial regions can't bear qualities its unlikely this will change. Closing WONTFIX
