### ISSUE TITLE
[ild-1]: comment is misleading wrt axiom

### ISSUE THREAD

**Issue by wceusters** [BFO-ontology/BFO-2020#93]
(cl:comment "participates-in is time indexed and has domain: independent-continuant but not spatial-region or specifically-dependent-continuant or generically-dependent-continuant  and range: process [ild-1]"
    (forall (a b t)
     (if (participates-in a b t)
      (and
       (or
        (and (instance-of a independent-continuant t)
         (not (instance-of a spatial-region t)))
        (instance-of a specifically-dependent-continuant t)
        (instance-of a generically-dependent-continuant t))
       (instance-of b process t) (instance-of t temporal-region t)))))

It is easy to interpret the comment differently than what the axiom says and this because of the use of 'and' and 'or' in the comment. So people not reading the axiom, and only the comment, might get it wrong.
Better comment phrasing: "participates-in is time indexed and has domain: (a) independent-continuant but not spatial-region or, (b) specifically-dependent-continuant or (c) generically-dependent-continuant,  and range: process [ild-1]"
This avoids the erroneous reading "participates-in is time indexed and has domain: independent-continuant but not (a) spatial-region or (b) specifically-dependent-continuant or (c) generically-dependent-continuant,  and range: process [ild-1]"

**Comment by alanruttenberg** [comment]
The documentation for that is autogenerated. I could fix the generator, but it's easier to reorder the arguments. Is this ok?

>participates-in is time indexed and has domain: independent-continuant or specifically-dependent-continuant or generically-dependent-continuant but not spatial-region and range: process [ild-1]

**Comment by wceusters** [comment]
> The documentation for that is autogenerated. I could fix the generator, but it's easier to reorder the arguments. Is this ok?
> 
> > participates-in is time indexed and has domain: independent-continuant or specifically-dependent-continuant or generically-dependent-continuant but not spatial-region and range: process [ild-1]

Yes.
